// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_net_JarURLConnection__
#define __java_net_JarURLConnection__

#pragma interface

#include <java/net/URLConnection.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace security
    {
      namespace cert
      {
        class Certificate;
      }
    }
    namespace net
    {
      class JarURLConnection;
      class URLConnection;
      class URL;
    }
  }
};

class ::java::net::JarURLConnection : public ::java::net::URLConnection
{
public:
  virtual ::java::net::URL *getJarFileURL () { return jarFileURL; }
  virtual ::java::lang::String *getEntryName () { return element; }
public:  // actually protected
  JarURLConnection (::java::net::URL *);
public:
  virtual void connect ();
  virtual ::java::io::InputStream *getInputStream ();
  virtual ::java::util::jar::JarEntry *getJarEntry ();
  virtual ::java::util::jar::JarFile *getJarFile () = 0;
  virtual ::java::lang::String *getHeaderField (::java::lang::String *);
  virtual ::java::util::Map *getHeaderFields ();
  virtual ::java::lang::String *getHeaderField (jint);
  virtual ::java::lang::String *getHeaderFieldKey (jint);
private:
  ::java::lang::String *getKey (::java::lang::String *);
  ::java::lang::String *getField (::java::lang::String *);
  void getHeaders ();
public:
  virtual JArray< ::java::security::cert::Certificate *> *getCertificates ();
  virtual ::java::util::jar::Attributes *getMainAttributes ();
  virtual ::java::util::jar::Attributes *getAttributes () { return 0; }
  virtual ::java::util::jar::Manifest *getManifest ();
private:
  ::java::net::URL * __attribute__((aligned(__alignof__( ::java::net::URLConnection )))) jarFileURL;
public:  // actually protected
  ::java::net::URLConnection *jarFileURLConnection;
private:
  ::java::lang::String *element;
public: // actually package-private
  static ::java::util::Hashtable *conn_cache;
private:
  ::java::util::Hashtable *hdrHash;
  ::java::util::Vector *hdrVec;
  jboolean gotHeaders;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_net_JarURLConnection__ */
