# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = /home/yanxin/git/jrate/gcc/libjava/gcj
top_srcdir = /home/yanxin/git/jrate/gcc/libjava
VPATH = /home/yanxin/git/jrate/gcc/libjava/gcj
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/libjava
pkglibdir = $(libdir)/libjava
pkgincludedir = $(includedir)/libjava

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /bin/sh /home/yanxin/git/jrate/gcc/install-sh -c
INSTALL_PROGRAM = /bin/sh /home/yanxin/git/jrate/gcc/install-sh -c  $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = /bin/sh /home/yanxin/git/jrate/gcc/install-sh -c -m 644
INSTALL_SCRIPT = /bin/sh /home/yanxin/git/jrate/gcc/install-sh -c
transform = s,^,jRate-,; 

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
AR = ar
AS = as
BACKTRACESPEC = 
CC = /home/yanxin/git/jrate/gcc-build/gcc/xgcc -B/home/yanxin/git/jrate/gcc-build/gcc/ -B/usr/local/i686-pc-linux-gnu/bin/ -B/usr/local/i686-pc-linux-gnu/lib/ -isystem /usr/local/i686-pc-linux-gnu/include
CHECKREFSPEC = 
COMPPATH = ..
CXX = /home/yanxin/git/jrate/gcc-build/gcc/xgcc -shared-libgcc -B/home/yanxin/git/jrate/gcc-build/gcc/ -nostdinc++  -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src/.libs -B/usr/local/i686-pc-linux-gnu/bin/ -B/usr/local/i686-pc-linux-gnu/lib/ -isystem /usr/local/i686-pc-linux-gnu/include
CXXCPP = /home/yanxin/git/jrate/gcc-build/gcc/xgcc -shared-libgcc -B/home/yanxin/git/jrate/gcc-build/gcc/ -nostdinc++  -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src/.libs -B/usr/local/i686-pc-linux-gnu/bin/ -B/usr/local/i686-pc-linux-gnu/lib/ -isystem /usr/local/i686-pc-linux-gnu/include -E
DIRLTDL = libltdl
DIVIDESPEC = -fno-use-divide-subroutine
DLLTOOL = @DLLTOOL@
EXCEPTIONSPEC = -fnon-call-exceptions
EXEEXT = 
GCC_UNWIND_INCLUDE = -I$(libgcj_basedir)/../gcc
GCDEPS = 
GCINCS = 
GCJ = /home/yanxin/git/jrate/gcc-build/gcc/gcj -B/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libjava/ -B/home/yanxin/git/jrate/gcc-build/gcc/
GCJFLAGS = -g -O2
GCJVERSION = 3.3.3
GCLIBS = 
GCOBJS = jRate-gc.lo
GCSPEC = 
GCTESTSPEC = 
HASH_SYNC_SPEC = 
IEEESPEC = 
INCLTDL = -I$(top_srcdir)/libltdl -I${top_srcdir}/libltdl
INTERPRETER = no
JC1GCSPEC = 
LIBFFI = ../libffi/libffi_convenience.la
LIBFFIINCS = -I$(top_srcdir)/../libffi/include -I../libffi/include
LIBGCJDEBUG = false
LIBGCJTESTSPEC = -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libjava/.libs -rpath /home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libjava/.libs
LIBGCJ_CFLAGS = -D__NO_MATH_INLINES  -ffloat-store
LIBGCJ_CXXFLAGS = -D__NO_MATH_INLINES  -ffloat-store
LIBGCJ_JAVAFLAGS =   -ffloat-store
LIBICONV = 
LIBLTDL = ${top_builddir}/libltdl/libltdlc.la
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
MAKEINFO = /home/yanxin/git/jrate/gcc/missing makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = libjava
PERL = perl
PLATFORMOBJS = posix.lo
RANLIB = ranlib
STRIP = strip
SYSDEP_SOURCES = 
SYSTEMSPEC =  
SYS_ZLIBS = 
THREADDEPS = 
THREADINCS = 
THREADLDFLAGS = 
THREADLIBS = -lpthread
THREADOBJS = posix-threads.lo
THREADSPEC = -lpthread
VERSION = 0.0.7
ZINCS = -I$(top_srcdir)/../zlib
ZLIBS = ../zlib/libzgcj_convenience.la
ZLIBSPEC = 
ZLIBTESTSPEC = 
gcc_version = 3.3.3
glibjava_CXX = /home/yanxin/git/jrate/gcc-build/gcc/xgcc -shared-libgcc -B/home/yanxin/git/jrate/gcc-build/gcc/ -nostdinc++  -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src/.libs -B/usr/local/i686-pc-linux-gnu/bin/ -B/usr/local/i686-pc-linux-gnu/lib/ -isystem /usr/local/i686-pc-linux-gnu/include
here = /home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libjava
libgcj_basedir = /home/yanxin/git/jrate/gcc/libjava/.././libjava
mkinstalldirs = /home/yanxin/git/jrate/gcc/mkinstalldirs
tool_include_dir = $(libdir)/gcc-lib/$(target_alias)/3.3.3/include
toolexecdir = $(libdir)/gcc-lib/$(target_alias)
toolexeclibdir = $(libdir)/.
toolexecmainlibdir = $(libdir)

AUTOMAKE_OPTIONS = foreign

gcjdir = $(includedir)/gcj
gcj_HEADERS = array.h cni.h field.h javaprims.h method.h

toolgcjdir = $(libdir)/gcc-lib/$(target_alias)/3.3.3/include/gcj
toolgcj_HEADERS = libgcj-config.h
CONFIG_HEADER = ../include/config.h libgcj-config.h
CONFIG_CLEAN_FILES = 
HEADERS =  $(gcj_HEADERS) $(toolgcj_HEADERS)

DIST_COMMON =  ./stamp-h2.in Makefile.am Makefile.in libgcj-config.h.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --foreign gcj/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


libgcj-config.h: stamp-h2
	@if test ! -f $@; then \
		rm -f stamp-h2; \
		$(MAKE) stamp-h2; \
	else :; fi
stamp-h2: $(srcdir)/libgcj-config.h.in $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES= CONFIG_HEADERS=gcj/libgcj-config.h \
	     $(SHELL) ./config.status
	@echo timestamp > stamp-h2 2> /dev/null
$(srcdir)/libgcj-config.h.in: #$(srcdir)/stamp-h2.in
	@if test ! -f $@; then \
		rm -f $(srcdir)/stamp-h2.in; \
		$(MAKE) $(srcdir)/stamp-h2.in; \
	else :; fi
$(srcdir)/stamp-h2.in: $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOHEADER)
	@echo timestamp > $(srcdir)/stamp-h2.in 2> /dev/null

mostlyclean-hdr:

clean-hdr:

distclean-hdr:
	-rm -f libgcj-config.h

maintainer-clean-hdr:

install-gcjHEADERS: $(gcj_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(gcjdir)
	@list='$(gcj_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(gcjdir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(gcjdir)/$$p; \
	done

uninstall-gcjHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(gcj_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(gcjdir)/$$p; \
	done

install-toolgcjHEADERS: $(toolgcj_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(toolgcjdir)
	@list='$(toolgcj_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(toolgcjdir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(toolgcjdir)/$$p; \
	done

uninstall-toolgcjHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(toolgcj_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(toolgcjdir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES) libgcj-config.h.in $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)libgcj-config.h.in$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags libgcj-config.h.in $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = gcj

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --foreign gcj/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
all-recursive-am: libgcj-config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

install-exec-am:
install-exec: install-exec-am

install-data-am: install-gcjHEADERS install-toolgcjHEADERS
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-gcjHEADERS uninstall-toolgcjHEADERS
uninstall: uninstall-am
all-am: Makefile $(HEADERS) libgcj-config.h
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(gcjdir) $(DESTDIR)$(toolgcjdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-hdr mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-hdr clean-tags clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-hdr distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-hdr maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-hdr distclean-hdr clean-hdr maintainer-clean-hdr \
uninstall-gcjHEADERS install-gcjHEADERS uninstall-toolgcjHEADERS \
install-toolgcjHEADERS tags mostlyclean-tags distclean-tags clean-tags \
maintainer-clean-tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck all-recursive-am install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
