// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_gcj_protocol_http_Connection__
#define __gnu_gcj_protocol_http_Connection__

#pragma interface

#include <java/net/HttpURLConnection.h>

extern "Java"
{
  namespace gnu
  {
    namespace gcj
    {
      namespace protocol
      {
        namespace http
        {
          class Connection;
        }
      }
    }
  }
  namespace java
  {
    namespace net
    {
      class URL;
      class Socket;
    }
  }
};

class ::gnu::gcj::protocol::http::Connection : public ::java::net::HttpURLConnection
{
public:
  Connection (::java::net::URL *);
  static void setDefaultRequestProperty (::java::lang::String *, ::java::lang::String *);
  static ::java::lang::String *getDefaultRequestProperty (::java::lang::String *);
  virtual void setRequestProperty (::java::lang::String *, ::java::lang::String *);
  virtual ::java::lang::String *getRequestProperty (::java::lang::String *);
  virtual void connect ();
  virtual void disconnect ();
  virtual jboolean usingProxy ();
  virtual ::java::io::InputStream *getInputStream ();
  virtual ::java::io::OutputStream *getOutputStream ();
  virtual ::java::lang::String *getHeaderField (::java::lang::String *);
  virtual ::java::util::Map *getHeaderFields ();
  virtual ::java::lang::String *getHeaderField (jint);
  virtual ::java::lang::String *getHeaderFieldKey (jint);
private:
  ::java::lang::String *getKey (::java::lang::String *);
  ::java::lang::String *getField (::java::lang::String *);
  void getHttpHeaders ();
public:  // actually protected
  ::java::net::Socket * __attribute__((aligned(__alignof__( ::java::net::HttpURLConnection )))) sock;
private:
  static ::java::util::Hashtable *defRequestProperties;
  ::java::util::Hashtable *requestProperties;
  ::java::util::Hashtable *hdrHash;
  ::java::util::Vector *hdrVec;
  ::java::io::BufferedInputStream *bufferedIn;
  static jint proxyPort;
  static jboolean proxyInUse;
  static ::java::lang::String *proxyHost;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_gcj_protocol_http_Connection__ */
