// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_gcj_runtime_AddressHolder__
#define __gnu_gcj_runtime_AddressHolder__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace gnu
  {
    namespace gcj
    {
      namespace runtime
      {
        class AddressHolder;
      }
      class RawData;
    }
  }
};

class ::gnu::gcj::runtime::AddressHolder : public ::java::lang::Object
{
public:
  AddressHolder ();
  AddressHolder (::gnu::gcj::RawData *);
  virtual void setAddress (::gnu::gcj::RawData *);
  virtual ::gnu::gcj::RawData *getAddress () { return address; }
  virtual jboolean equals (::gnu::gcj::runtime::AddressHolder *);
  virtual jboolean equals (::java::lang::Object *);
  virtual jint hashCode ();
private:
  ::gnu::gcj::RawData * __attribute__((aligned(__alignof__( ::java::lang::Object )))) address;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_gcj_runtime_AddressHolder__ */
