// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_gcj_runtime_FinalizerThread__
#define __gnu_gcj_runtime_FinalizerThread__

#pragma interface

#include <java/lang/Thread.h>

extern "Java"
{
  namespace gnu
  {
    namespace gcj
    {
      namespace runtime
      {
        class FinalizerThread;
      }
    }
  }
};

class ::gnu::gcj::runtime::FinalizerThread : public ::java::lang::Thread
{
public:
  FinalizerThread ();
  static void finalizerReady ();
private:
  static void runFinalizers ();
public:
  void run ();
private:
  static ::java::lang::Object *lock;
  static jboolean thread_started;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_gcj_runtime_FinalizerThread__ */
