// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_security_provider_DERReader__
#define __gnu_java_security_provider_DERReader__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace security
      {
        namespace provider
        {
          class DERReader;
        }
      }
    }
  }
  namespace java
  {
    namespace math
    {
      class BigInteger;
    }
  }
};

class ::gnu::java::security::provider::DERReader : public ::java::lang::Object
{
public:
  DERReader ();
  DERReader (jbyteArray);
  virtual void init (::java::lang::String *);
  virtual void init (jbyteArray);
  virtual ::java::math::BigInteger *getBigInteger ();
private:
  jbyteArray getPrimitive ();
  jint translateLeadIdentifierByte (jbyte);
  jint getIdentifier (jint);
public: // actually package-private
  jbyteArray __attribute__((aligned(__alignof__( ::java::lang::Object ))))  source;
  jint pos;
  static const jint UNIVERSAL = 1L;
  static const jint APPLICATION = 2L;
  static const jint CONTEXT_SPECIFIC = 3L;
  static const jint PRIVATE = 4L;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_security_provider_DERReader__ */
