// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_AbsoluteTime__
#define __javax_realtime_AbsoluteTime__

#pragma interface

#include <javax/realtime/HighResolutionTime.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class Clock;
      class RelativeTime;
      class AbsoluteTime;
    }
  }
};

class ::javax::realtime::AbsoluteTime : public ::javax::realtime::HighResolutionTime
{
public:
  AbsoluteTime ();
  AbsoluteTime (jlong, jint);
  AbsoluteTime (::javax::realtime::AbsoluteTime *);
  AbsoluteTime (::java::util::Date *);
  virtual ::javax::realtime::AbsoluteTime *add (jlong, jint);
  virtual void add (jlong, jint, ::javax::realtime::AbsoluteTime *);
  ::javax::realtime::AbsoluteTime *add (::javax::realtime::RelativeTime *);
  void add (::javax::realtime::RelativeTime *, ::javax::realtime::AbsoluteTime *);
  virtual void increment (::javax::realtime::RelativeTime *);
  virtual void decrement (::javax::realtime::RelativeTime *);
  virtual ::java::util::Date *getDate ();
  virtual ::javax::realtime::RelativeTime *relative (::javax::realtime::Clock *);
  ::javax::realtime::RelativeTime *subtract (::javax::realtime::AbsoluteTime *);
  void subtract (::javax::realtime::AbsoluteTime *, ::javax::realtime::RelativeTime *);
  ::javax::realtime::AbsoluteTime *subtract (::javax::realtime::RelativeTime *);
  void subtract (::javax::realtime::RelativeTime *, ::javax::realtime::AbsoluteTime *);
  virtual ::java::lang::String *toString ();

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_AbsoluteTime__ */
