// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_AccessViolationError__
#define __javax_realtime_AccessViolationError__

#pragma interface

#include <java/lang/Error.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class AccessViolationError;
    }
  }
};

class ::javax::realtime::AccessViolationError : public ::java::lang::Error
{
public:
  AccessViolationError ();
  AccessViolationError (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_AccessViolationError__ */
