// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_AperiodicParameters__
#define __javax_realtime_AperiodicParameters__

#pragma interface

#include <javax/realtime/ReleaseParameters.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class AperiodicParameters;
      class AsyncEventHandler;
      class RelativeTime;
    }
  }
};

class ::javax::realtime::AperiodicParameters : public ::javax::realtime::ReleaseParameters
{
public:
  AperiodicParameters (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::AsyncEventHandler *, ::javax::realtime::AsyncEventHandler *);
  virtual jboolean setIfFeasible (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_AperiodicParameters__ */
