// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_Arena__
#define __javax_realtime_Arena__

#pragma interface

#include <javax/realtime/MemoryArea.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class Arena;
      class SizeEstimator;
    }
  }
};

class ::javax::realtime::Arena : public ::javax::realtime::MemoryArea
{
public:  // actually protected
  Arena (jlong);
  Arena (::javax::realtime::SizeEstimator *);
  Arena (jlong, ::java::lang::Runnable *);
  Arena (::javax::realtime::SizeEstimator *, ::java::lang::Runnable *);
public:
  virtual jlong getMaximumSize () { return sizeInBytes; }
  virtual ::java::lang::Object *getPortal ();
  virtual void setPortal (::java::lang::Object *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_Arena__ */
