// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_ArenaFactory__
#define __javax_realtime_ArenaFactory__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class SizeEstimator;
      class RefCountedArena;
      class ArenaFactory;
    }
  }
};

class ::javax::realtime::ArenaFactory : public ::java::lang::Object
{
public:  // actually protected
  ArenaFactory ();
public:
  static ::javax::realtime::ArenaFactory *instance ();
  static ::javax::realtime::RefCountedArena *createRefCountedArena (jlong);
  static ::javax::realtime::RefCountedArena *createRefCountedArena (::javax::realtime::SizeEstimator *);
  static ::javax::realtime::RefCountedArena *createRefCountedArena (jlong, ::java::lang::Runnable *);
  static ::javax::realtime::RefCountedArena *createRefCountedArena (::javax::realtime::SizeEstimator *, ::java::lang::Runnable *);
public:  // actually protected
  static ::javax::realtime::ArenaFactory *theInstance;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_ArenaFactory__ */
