// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_AsynchronouslyInterruptedException__
#define __javax_realtime_AsynchronouslyInterruptedException__

#pragma interface

#include <java/lang/InterruptedException.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class AsynchronouslyInterruptedException;
    }
  }
};

class ::javax::realtime::AsynchronouslyInterruptedException : public ::java::lang::InterruptedException
{
public:
  AsynchronouslyInterruptedException ();

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_AsynchronouslyInterruptedException__ */
