// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_AsyncEvent__
#define __javax_realtime_AsyncEvent__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class AsyncEvent;
      class AsyncEventHandler;
      class ReleaseParameters;
      class PriorityQueue$ForwardIterator;
      class PriorityQueue;
    }
  }
};

class ::javax::realtime::AsyncEvent : public ::java::lang::Object
{
public:
  AsyncEvent ();
  AsyncEvent (::javax::realtime::ReleaseParameters *);
  virtual void addHandler (::javax::realtime::AsyncEventHandler *);
  virtual void bindTo (::java::lang::String *);
  virtual ::javax::realtime::ReleaseParameters *createReleaseParameters ();
  virtual void fire ();
  virtual jboolean handledBy (::javax::realtime::AsyncEventHandler *);
  virtual void removeHandler (::javax::realtime::AsyncEventHandler *);
  virtual void setHandler (::javax::realtime::AsyncEventHandler *);
  virtual void unbindTo (::java::lang::String *);
public:  // actually protected
  ::javax::realtime::PriorityQueue * __attribute__((aligned(__alignof__( ::java::lang::Object )))) handlerList;
  ::javax::realtime::PriorityQueue$ForwardIterator *listIterator;
  ::javax::realtime::ReleaseParameters *releaseParams;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_AsyncEvent__ */
