// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_Clock__
#define __javax_realtime_Clock__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class OneShotTimerImpl;
      class OneShotTimer;
      class PeriodicTimerImpl;
      class PeriodicTimer;
      class RelativeTime;
      class Clock;
      class AbsoluteTime;
    }
  }
};

class ::javax::realtime::Clock : public ::java::lang::Object
{
public:
  static ::javax::realtime::Clock *getRealtimeClock ();
  virtual ::javax::realtime::RelativeTime *getResolution () = 0;
  virtual void setResolution (::javax::realtime::RelativeTime *) = 0;
  virtual ::javax::realtime::AbsoluteTime *getTime ();
  virtual void getTime (::javax::realtime::AbsoluteTime *) = 0;
  virtual ::javax::realtime::RelativeTime *relative (::javax::realtime::AbsoluteTime *);
  virtual void relative (::javax::realtime::AbsoluteTime *, ::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::AbsoluteTime *absolute (::javax::realtime::RelativeTime *);
  virtual void absolute (::javax::realtime::RelativeTime *, ::javax::realtime::AbsoluteTime *);
public: // actually package-private
  virtual ::javax::realtime::PeriodicTimerImpl *createPeriodicTimerImpl (::javax::realtime::PeriodicTimer *, ::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *) = 0;
  virtual ::javax::realtime::PeriodicTimerImpl *createPeriodicTimerImpl (::javax::realtime::PeriodicTimer *, ::javax::realtime::AbsoluteTime *, ::javax::realtime::RelativeTime *) = 0;
  virtual ::javax::realtime::OneShotTimerImpl *createOneShotTimerImpl (::javax::realtime::OneShotTimer *, ::javax::realtime::RelativeTime *) = 0;
  virtual ::javax::realtime::OneShotTimerImpl *createOneShotTimerImpl (::javax::realtime::OneShotTimer *, ::javax::realtime::AbsoluteTime *) = 0;
public:
  Clock ();
private:
  ::javax::realtime::AbsoluteTime * __attribute__((aligned(__alignof__( ::java::lang::Object )))) tempAbsTime;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_Clock__ */
