// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_CTMemory__
#define __javax_realtime_CTMemory__

#pragma interface

#include <javax/realtime/ScopedMemory.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class CTMemory;
      class SizeEstimator;
    }
  }
};

class ::javax::realtime::CTMemory : public ::javax::realtime::ScopedMemory
{
public:
  CTMemory (jlong, jlong);
  CTMemory (jlong);
  CTMemory (jlong, ::java::lang::Runnable *);
  CTMemory (::javax::realtime::SizeEstimator *);
  CTMemory (::javax::realtime::SizeEstimator *, ::java::lang::Runnable *);
  virtual jlong memoryConsumed ();
  virtual jlong memoryRemaining ();
public:  // actually protected
  virtual void init ();
  virtual void fini ();
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_CTMemory__ */
