// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_CTPrivateMemory__
#define __javax_realtime_CTPrivateMemory__

#pragma interface

#include <javax/realtime/PrivateScopedMemory.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class CTPrivateMemory;
      class SizeEstimator;
    }
  }
};

class ::javax::realtime::CTPrivateMemory : public ::javax::realtime::PrivateScopedMemory
{
public:
  CTPrivateMemory (jlong, jlong);
  CTPrivateMemory (jlong);
  CTPrivateMemory (jlong, ::java::lang::Runnable *);
  CTPrivateMemory (::javax::realtime::SizeEstimator *);
  CTPrivateMemory (::javax::realtime::SizeEstimator *, ::java::lang::Runnable *);
  virtual jlong memoryConsumed ();
  virtual jlong memoryRemaining ();
public:  // actually protected
  virtual void init ();
  virtual void fini ();
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_CTPrivateMemory__ */
