// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_ExecutionEligibilityParameters__
#define __javax_realtime_ExecutionEligibilityParameters__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class ExecutionEligibilityParameters;
    }
  }
};

class ::javax::realtime::ExecutionEligibilityParameters : public ::java::lang::Object
{
public:
  ExecutionEligibilityParameters (jint);
  ExecutionEligibilityParameters ();
  virtual jint getExecutionEligibility () { return eligibility; }
  virtual void setExecutionEligibility (jint);
private:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  eligibility;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_ExecutionEligibilityParameters__ */
