// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_HeapMemory__
#define __javax_realtime_HeapMemory__

#pragma interface

#include <javax/realtime/MemoryArea.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class HeapMemory;
    }
  }
};

class ::javax::realtime::HeapMemory : public ::javax::realtime::MemoryArea
{
public:
  jlong memoryConsumed ();
  jlong memoryRemaining ();
private:
  HeapMemory ();
public:
  static ::javax::realtime::HeapMemory *instance ();
public:  // actually protected
  void init ();
  void fini ();
private:
  static ::javax::realtime::HeapMemory *theInstance;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_HeapMemory__ */
