// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_HighResolutionTimer__
#define __javax_realtime_HighResolutionTimer__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class HighResolutionTimer;
      class RelativeTime;
      class HighResolutionClock;
    }
  }
};

class ::javax::realtime::HighResolutionTimer : public ::java::lang::Object
{
public:
  virtual void start ();
  virtual void stop ();
  virtual void reset ();
  virtual ::javax::realtime::RelativeTime *getElapsedTime ();
  virtual void getElapsedTime (::javax::realtime::RelativeTime *);
  HighResolutionTimer ();
public: // actually package-private
  jlong __attribute__((aligned(__alignof__( ::java::lang::Object ))))  startClockTick;
  jlong stopClockTick;
  ::javax::realtime::HighResolutionClock *clock;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_HighResolutionTimer__ */
