// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_IllegalAssignmentError__
#define __javax_realtime_IllegalAssignmentError__

#pragma interface

#include <java/lang/Error.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class IllegalAssignmentError;
    }
  }
};

class ::javax::realtime::IllegalAssignmentError : public ::java::lang::Error
{
public:
  IllegalAssignmentError ();
  IllegalAssignmentError (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_IllegalAssignmentError__ */
