// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_ImmortalMemory__
#define __javax_realtime_ImmortalMemory__

#pragma interface

#include <javax/realtime/MemoryArea.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class ImmortalMemory;
    }
  }
};

class ::javax::realtime::ImmortalMemory : public ::javax::realtime::MemoryArea
{
private:
  ImmortalMemory (jlong);
  ImmortalMemory ();
public:
  static ::javax::realtime::ImmortalMemory *instance ();
  jlong memoryConsumed ();
  jlong memoryRemaining ();
public:  // actually protected
  void init ();
  void fini ();
public: // actually package-private
  static ::javax::realtime::ImmortalMemory *theInstance;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_ImmortalMemory__ */
