// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_InaccessibleAreaException__
#define __javax_realtime_InaccessibleAreaException__

#pragma interface

#include <java/lang/RuntimeException.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class InaccessibleAreaException;
    }
  }
};

class ::javax::realtime::InaccessibleAreaException : public ::java::lang::RuntimeException
{
public:
  InaccessibleAreaException ();
  InaccessibleAreaException (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_InaccessibleAreaException__ */
