// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_LTMemory__
#define __javax_realtime_LTMemory__

#pragma interface

#include <javax/realtime/ScopedMemory.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class LTMemory;
      class SizeEstimator;
    }
  }
};

class ::javax::realtime::LTMemory : public ::javax::realtime::ScopedMemory
{
public:
  LTMemory (jlong, jlong);
  LTMemory (::javax::realtime::SizeEstimator *, ::java::lang::Runnable *);
  LTMemory (jlong, ::java::lang::Runnable *);
  virtual jlong memoryConsumed ();
  virtual jlong memoryRemaining ();
public:  // actually protected
  virtual void init ();
  virtual void fini ();
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_LTMemory__ */
