// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_LTPrivateMemory__
#define __javax_realtime_LTPrivateMemory__

#pragma interface

#include <javax/realtime/PrivateScopedMemory.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class LTPrivateMemory;
      class SizeEstimator;
    }
  }
};

class ::javax::realtime::LTPrivateMemory : public ::javax::realtime::PrivateScopedMemory
{
public:
  LTPrivateMemory (jlong, jlong);
  LTPrivateMemory (jlong);
  LTPrivateMemory (jlong, ::java::lang::Runnable *);
  LTPrivateMemory (::javax::realtime::SizeEstimator *);
  LTPrivateMemory (::javax::realtime::SizeEstimator *, ::java::lang::Runnable *);
  virtual jlong memoryConsumed ();
  virtual jlong memoryRemaining ();
public:  // actually protected
  virtual void init ();
  virtual void fini ();
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_LTPrivateMemory__ */
