// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_MemoryAccessError__
#define __javax_realtime_MemoryAccessError__

#pragma interface

#include <java/lang/Error.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class MemoryAccessError;
    }
  }
};

class ::javax::realtime::MemoryAccessError : public ::java::lang::Error
{
public:
  MemoryAccessError ();
  MemoryAccessError (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_MemoryAccessError__ */
