// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_MemoryParameters__
#define __javax_realtime_MemoryParameters__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class MemoryParameters;
    }
  }
};

class ::javax::realtime::MemoryParameters : public ::java::lang::Object
{
public:
  MemoryParameters (jlong, jlong);
  MemoryParameters (jlong, jlong, jlong);
  virtual jlong getAllocationRate () { return allocationRate; }
  virtual void setAllocationRate (jlong);
  virtual jboolean setAllocationRateIfFeasible (jint);
  virtual jlong getMaxImmortal () { return maxImmortal; }
  virtual jboolean setMaxImmortalIfFeasible (jlong);
  virtual jboolean setMaxMemoryAreaIfFeasible (jlong);
public:  // actually protected
  jlong __attribute__((aligned(__alignof__( ::java::lang::Object ))))  maxMemoryArea;
  jlong maxImmortal;
  jlong allocationRate;
public:
  static const jlong NO_MAX = -1LL;

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_MemoryParameters__ */
