// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_MemoryArea__
#define __javax_realtime_MemoryArea__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace gcj
    {
      class RawData;
    }
  }
  namespace javax
  {
    namespace realtime
    {
      class SizeEstimator;
      class MemoryArea;
    }
  }
};

class ::javax::realtime::MemoryArea : public ::java::lang::Object
{
public:  // actually protected
  MemoryArea ();
  MemoryArea (jlong);
  MemoryArea (jlong, ::java::lang::Runnable *);
  MemoryArea (::javax::realtime::SizeEstimator *);
  MemoryArea (::javax::realtime::SizeEstimator *, ::java::lang::Runnable *);
public:
  virtual void enter ();
  virtual void enter (::java::lang::Runnable *);
public:  // actually protected
  void guardedRun (::java::lang::Runnable *);
public:
  virtual void executeInArea (::java::lang::Runnable *);
  static ::javax::realtime::MemoryArea *getMemoryArea (::java::lang::Object *);
  virtual jlong memoryConsumed () = 0;
  virtual jlong memoryRemaining () = 0;
  virtual ::java::lang::Object *newArray (::java::lang::Class *, jint);
public: // actually package-private
  virtual ::java::lang::Object *unchecked_newArray (::java::lang::Class *, jint);
public:
  virtual ::java::lang::Object *newInstance (::java::lang::Class *);
public: // actually package-private
  virtual ::java::lang::Object *unchecked_newInstance (::java::lang::Class *);
public:
  virtual ::java::lang::Object *newInstance (::java::lang::reflect::Constructor *, JArray< ::java::lang::Object *> *);
public: // actually package-private
  virtual ::java::lang::Object *unchecked_newInstance (::java::lang::reflect::Constructor *, JArray< ::java::lang::Object *> *);
public:
  virtual jlong size () { return sizeInBytes; }
public:  // actually protected
  virtual void init () = 0;
  virtual void fini () = 0;
  virtual void finalize ();
  jlong __attribute__((aligned(__alignof__( ::java::lang::Object ))))  sizeInBytes;
  ::java::lang::Runnable *logic;
  ::javax::realtime::MemoryArea *parent;
public: // actually package-private
  ::gnu::gcj::RawData *ma_;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_MemoryArea__ */
