// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_MethodAreaMemory__
#define __javax_realtime_MethodAreaMemory__

#pragma interface

#include <javax/realtime/MemoryArea.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class MethodAreaMemory;
    }
  }
};

class ::javax::realtime::MethodAreaMemory : public ::javax::realtime::MemoryArea
{
public:
  static ::javax::realtime::MethodAreaMemory *instance ();
  virtual jlong memoryConsumed ();
  virtual jlong memoryRemaining ();
private:
  MethodAreaMemory ();
public:  // actually protected
  virtual void init ();
  virtual void fini ();
private:
  static ::javax::realtime::MethodAreaMemory *theInstance;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_MethodAreaMemory__ */
