// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_NoHeapRealtimeThread__
#define __javax_realtime_NoHeapRealtimeThread__

#pragma interface

#include <javax/realtime/RealtimeThread.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class NoHeapRealtimeThread;
      class ProcessingGroupParameters;
      class MemoryParameters;
      class ReleaseParameters;
      class MemoryArea;
      class SchedulingParameters;
    }
  }
};

class ::javax::realtime::NoHeapRealtimeThread : public ::javax::realtime::RealtimeThread
{
public:
  NoHeapRealtimeThread (::javax::realtime::SchedulingParameters *, ::javax::realtime::MemoryArea *);
  NoHeapRealtimeThread (::javax::realtime::SchedulingParameters *, ::javax::realtime::ReleaseParameters *, ::javax::realtime::MemoryArea *);
  NoHeapRealtimeThread (::javax::realtime::SchedulingParameters *, ::javax::realtime::ReleaseParameters *, ::javax::realtime::MemoryParameters *, ::javax::realtime::MemoryArea *, ::javax::realtime::ProcessingGroupParameters *, ::java::lang::Runnable *);
  NoHeapRealtimeThread ();
  NoHeapRealtimeThread (::java::lang::Runnable *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_NoHeapRealtimeThread__ */
