// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_OneShotTimerImpl__
#define __javax_realtime_OneShotTimerImpl__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class OneShotTimerImpl;
    }
  }
};

class ::javax::realtime::OneShotTimerImpl : public ::java::lang::Object
{
public:

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_realtime_OneShotTimerImpl__ */
