// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_PeriodicTimerImpl__
#define __javax_realtime_PeriodicTimerImpl__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class PeriodicTimerImpl;
      class RelativeTime;
    }
  }
};

class ::javax::realtime::PeriodicTimerImpl : public ::java::lang::Object
{
public:
  virtual ::javax::realtime::RelativeTime *getInterval () = 0;
  virtual void setInterval (::javax::realtime::RelativeTime *) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_realtime_PeriodicTimerImpl__ */
