// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_PeriodicTimerServer__
#define __javax_realtime_PeriodicTimerServer__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class PeriodicTimerServer;
      class PeriodicTimer;
    }
  }
};

class ::javax::realtime::PeriodicTimerServer : public ::java::lang::Object
{
public:
  virtual void registerTimer (::javax::realtime::PeriodicTimer *) = 0;
  virtual void unregisterTimer (::javax::realtime::PeriodicTimer *) = 0;
  virtual void schedule (::javax::realtime::PeriodicTimer *) = 0;
  virtual void deschedule (::javax::realtime::PeriodicTimer *) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_realtime_PeriodicTimerServer__ */
