// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_POSIXSignalHandler__
#define __javax_realtime_POSIXSignalHandler__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class POSIXSignalHandler;
      class AsyncEventHandler;
      class PriorityParameters;
      class RealtimeThread;
      class AsyncEvent;
    }
  }
  namespace gnu
  {
    namespace gcj
    {
      class RawData;
    }
  }
};

class ::javax::realtime::POSIXSignalHandler : public ::java::lang::Object
{
public:
  POSIXSignalHandler ();
  void addHandler (jint, ::javax::realtime::AsyncEventHandler *);
  void removeHandler (jint, ::javax::realtime::AsyncEventHandler *);
  void setHandler (jint, ::javax::realtime::AsyncEventHandler *);
public:  // actually protected
  void fireSignal (jint);
  void startDispatching ();
  void init ();
  void fini ();
  void registerNativeHandler (jint);
public:
  static const jint SIGHUP = 1L;
  static const jint SIGINT = 2L;
  static const jint SIGQUIT = 3L;
  static const jint SIGILL = 4L;
  static const jint SIGTRAP = 5L;
  static const jint SIGABRT = 6L;
  static const jint SIGIOT = 6L;
  static const jint SIGBUS = 7L;
  static const jint SIGFPE = 8L;
  static const jint SIGKILL = 9L;
  static const jint SIGUSR1 = 10L;
  static const jint SIGSEGV = 11L;
  static const jint SIGUSR2 = 12L;
  static const jint SIGPIPE = 13L;
  static const jint SIGALRM = 14L;
  static const jint SIGTERM = 15L;
  static const jint SIGSTKFLT = 16L;
  static const jint SIGCHLD = 17L;
  static const jint SIGCLD = 17L;
  static const jint SIGCONT = 18L;
  static const jint SIGSTOP = 19L;
  static const jint SIGTSTP = 20L;
  static const jint SIGTTIN = 21L;
  static const jint SIGTTOU = 22L;
  static const jint SIGURG = 23L;
  static const jint SIGXCPU = 24L;
  static const jint SIGXFSZ = 25L;
  static const jint SIGVTALRM = 26L;
  static const jint SIGPROF = 27L;
  static const jint SIGWINCH = 28L;
  static const jint SIGIO = 29L;
  static const jint SIGPOLL = 29L;
  static const jint SIGPWR = 30L;
  static const jint SIGSYS = 31L;
  static const jint SIGUNUSED = 31L;
public:  // actually protected
  static const jint SIGNUM = 31L;
  static const jint SIGMIN = 1L;
  static const jint SIGMAX = 31L;
  ::gnu::gcj::RawData * __attribute__((aligned(__alignof__( ::java::lang::Object )))) natHandler_;
  ::gnu::gcj::RawData *pipeID_;
  jboolean enabled_;
  JArray< ::javax::realtime::AsyncEvent *> *signalEvents;
  ::javax::realtime::RealtimeThread *notificationThread;
private:
  static ::javax::realtime::PriorityParameters *dispatcherPriority;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_POSIXSignalHandler__ */
