// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_PrimordialMemory__
#define __javax_realtime_PrimordialMemory__

#pragma interface

#include <javax/realtime/MemoryArea.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class PrimordialMemory;
    }
  }
};

class ::javax::realtime::PrimordialMemory : public ::javax::realtime::MemoryArea
{
public:
  PrimordialMemory ();

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_PrimordialMemory__ */
