// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_PriorityParameters__
#define __javax_realtime_PriorityParameters__

#pragma interface

#include <javax/realtime/SchedulingParameters.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class PriorityParameters;
    }
  }
};

class ::javax::realtime::PriorityParameters : public ::javax::realtime::SchedulingParameters
{
public:
  PriorityParameters (jint);
  virtual jint getPriority () { return priority; }
  virtual void setPriority (jint);
  virtual ::java::lang::String *toString ();
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::javax::realtime::SchedulingParameters ))))  priority;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_PriorityParameters__ */
