// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_PriorityQueue__
#define __javax_realtime_PriorityQueue__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class PriorityQueue;
      class PriorityQueue$ForwardIterator;
      class PriorityQueue$PriorityQueueLane;
    }
  }
};

class ::javax::realtime::PriorityQueue : public ::java::lang::Object
{
public:
  virtual ::javax::realtime::PriorityQueue$ForwardIterator *iterator ();
  virtual void iterator (::javax::realtime::PriorityQueue$ForwardIterator *);
  virtual void add (::java::lang::Object *, jint);
  virtual jboolean contains (::java::lang::Object *);
  virtual void remove (::java::lang::Object *);
  PriorityQueue ();
public:  // actually protected
  ::javax::realtime::PriorityQueue$PriorityQueueLane * __attribute__((aligned(__alignof__( ::java::lang::Object )))) queueHead;
  ::javax::realtime::PriorityQueue$PriorityQueueLane *queueTail;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_PriorityQueue__ */
