// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_ProcessingGroupParameters__
#define __javax_realtime_ProcessingGroupParameters__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class ProcessingGroupParameters;
      class AsyncEventHandler;
      class RelativeTime;
      class HighResolutionTime;
    }
  }
};

class ::javax::realtime::ProcessingGroupParameters : public ::java::lang::Object
{
public:
  ProcessingGroupParameters (::javax::realtime::HighResolutionTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::AsyncEventHandler *, ::javax::realtime::AsyncEventHandler *);
  virtual ::javax::realtime::RelativeTime *getCost () { return cost; }
  virtual void setCost (::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::AsyncEventHandler *getCostOverrunHandler () { return overrunHandler; }
  virtual void setCostOverrunHandler (::javax::realtime::AsyncEventHandler *);
  virtual ::javax::realtime::RelativeTime *getDeadline () { return deadline; }
  virtual void setDeadline (::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::AsyncEventHandler *getDeadlineMissHandler () { return missHandler; }
  virtual void setDeadlineMissHandler (::javax::realtime::AsyncEventHandler *);
  virtual ::javax::realtime::RelativeTime *getPeriod () { return period; }
  virtual void setPeriod (::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::HighResolutionTime *getStart () { return start; }
  virtual void setStart (::javax::realtime::HighResolutionTime *);
  virtual jboolean setIfFeasible (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *);
public:  // actually protected
  ::javax::realtime::HighResolutionTime * __attribute__((aligned(__alignof__( ::java::lang::Object )))) start;
  ::javax::realtime::RelativeTime *period;
  ::javax::realtime::RelativeTime *cost;
  ::javax::realtime::RelativeTime *deadline;
  ::javax::realtime::AsyncEventHandler *overrunHandler;
  ::javax::realtime::AsyncEventHandler *missHandler;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_ProcessingGroupParameters__ */
