// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_RationalTime__
#define __javax_realtime_RationalTime__

#pragma interface

#include <javax/realtime/RelativeTime.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class RationalTime;
      class AbsoluteTime;
      class RelativeTime;
    }
  }
};

class ::javax::realtime::RationalTime : public ::javax::realtime::RelativeTime
{
public:
  RationalTime (jint);
  RationalTime (jint, jlong, jint);
  RationalTime (jint, ::javax::realtime::RelativeTime *);
  virtual void addInterarrivalTo (::javax::realtime::AbsoluteTime *);
  virtual jint getFrequency () { return frequency; }
  virtual ::javax::realtime::RelativeTime *getInterarrivalTime ();
  virtual void getInterarrivalTime (::javax::realtime::RelativeTime *);
  virtual void set (jlong, jint);
  virtual void setFrequency (jint);
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::javax::realtime::RelativeTime ))))  frequency;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_RationalTime__ */
