// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_RealtimeClockPeriodicTimerImpl__
#define __javax_realtime_RealtimeClockPeriodicTimerImpl__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class RealtimeClockPeriodicTimerImpl;
      class HighResolutionTime;
      class ReleaseParameters;
      class RelativeTime;
      class AbsoluteTime;
      class RealtimeThread;
      class PeriodicTimer;
    }
  }
};

class ::javax::realtime::RealtimeClockPeriodicTimerImpl : public ::java::lang::Object
{
public: // actually package-private
  RealtimeClockPeriodicTimerImpl (::javax::realtime::PeriodicTimer *, ::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *);
public:
  virtual void start ();
  virtual void enable ();
  virtual void disable ();
  virtual void destroy ();
  virtual jboolean isRunning ();
  virtual jboolean stop ();
  virtual ::javax::realtime::AbsoluteTime *getFireTime ();
  virtual ::javax::realtime::ReleaseParameters *createReleaseParameters ();
  virtual ::javax::realtime::RelativeTime *getInterval ();
  virtual void setInterval (::javax::realtime::RelativeTime *);
  virtual void reschedule (::javax::realtime::HighResolutionTime *);
private:
  ::javax::realtime::PeriodicTimer * __attribute__((aligned(__alignof__( ::java::lang::Object )))) owner;
  ::javax::realtime::RealtimeThread *rtThread;
  ::javax::realtime::AbsoluteTime *startTime;
  ::javax::realtime::RelativeTime *period;
  jboolean isEnabled;
  jboolean isDone;
  jboolean isStarted;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_RealtimeClockPeriodicTimerImpl__ */
