// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_RealtimeClock__
#define __javax_realtime_RealtimeClock__

#pragma interface

#include <javax/realtime/Clock.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class OneShotTimerImpl;
      class OneShotTimer;
      class PeriodicTimerImpl;
      class PeriodicTimer;
      class AbsoluteTime;
      class RelativeTime;
      class RealtimeClock;
    }
  }
};

class ::javax::realtime::RealtimeClock : public ::javax::realtime::Clock
{
public:
  static ::javax::realtime::RealtimeClock *instance ();
  virtual ::javax::realtime::RelativeTime *getResolution ();
  virtual void setResolution (::javax::realtime::RelativeTime *);
  virtual void getTime (::javax::realtime::AbsoluteTime *);
private:
  void getTimeImpl (::javax::realtime::AbsoluteTime *);
  void setResolutionImpl (::javax::realtime::RelativeTime *);
  ::javax::realtime::RelativeTime *getResolutionImpl ();
public: // actually package-private
  virtual ::javax::realtime::PeriodicTimerImpl *createPeriodicTimerImpl (::javax::realtime::PeriodicTimer *, ::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::PeriodicTimerImpl *createPeriodicTimerImpl (::javax::realtime::PeriodicTimer *, ::javax::realtime::AbsoluteTime *, ::javax::realtime::RelativeTime *) { return 0; }
  virtual ::javax::realtime::OneShotTimerImpl *createOneShotTimerImpl (::javax::realtime::OneShotTimer *, ::javax::realtime::RelativeTime *) { return 0; }
  virtual ::javax::realtime::OneShotTimerImpl *createOneShotTimerImpl (::javax::realtime::OneShotTimer *, ::javax::realtime::AbsoluteTime *) { return 0; }
public:
  RealtimeClock ();
private:
  static ::javax::realtime::RealtimeClock *theInstance;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_RealtimeClock__ */
