// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_RefCountedArena__
#define __javax_realtime_RefCountedArena__

#pragma interface

#include <javax/realtime/Arena.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class RefCountedArena;
      class SizeEstimator;
    }
  }
};

class ::javax::realtime::RefCountedArena : public ::javax::realtime::Arena
{
public: // actually package-private
  RefCountedArena (jlong);
  RefCountedArena (::javax::realtime::SizeEstimator *);
  RefCountedArena (jlong, ::java::lang::Runnable *);
  RefCountedArena (::javax::realtime::SizeEstimator *, ::java::lang::Runnable *);
public:
  virtual jlong memoryConsumed ();
  virtual jlong memoryRemaining ();
public:  // actually protected
  virtual void init ();
  virtual void fini ();
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_RefCountedArena__ */
