// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_RelativeTime__
#define __javax_realtime_RelativeTime__

#pragma interface

#include <javax/realtime/HighResolutionTime.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class AbsoluteTime;
      class Clock;
      class RelativeTime;
    }
  }
};

class ::javax::realtime::RelativeTime : public ::javax::realtime::HighResolutionTime
{
public:
  RelativeTime ();
  RelativeTime (jlong, jint);
  RelativeTime (::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::AbsoluteTime *absolute (::javax::realtime::Clock *);
  virtual void absolute (::javax::realtime::Clock *, ::javax::realtime::AbsoluteTime *);
  ::javax::realtime::RelativeTime *add (::javax::realtime::RelativeTime *);
  virtual void add (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::RelativeTime *add (jlong, jint);
  virtual void add (jlong, jint, ::javax::realtime::RelativeTime *);
  ::javax::realtime::RelativeTime *subtract (::javax::realtime::RelativeTime *);
  void subtract (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *);
  virtual void increment (::javax::realtime::RelativeTime *);
  virtual void decrement (::javax::realtime::RelativeTime *);
  virtual ::java::lang::String *toString ();

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_RelativeTime__ */
