// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_ReleaseParameters__
#define __javax_realtime_ReleaseParameters__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class ReleaseParameters;
      class AsyncEventHandler;
      class RelativeTime;
    }
  }
};

class ::javax::realtime::ReleaseParameters : public ::java::lang::Object
{
public:  // actually protected
  ReleaseParameters ();
  ReleaseParameters (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::AsyncEventHandler *, ::javax::realtime::AsyncEventHandler *);
public:
  virtual ::javax::realtime::RelativeTime *getCost () { return cost; }
  virtual void setCost (::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::RelativeTime *getDeadline () { return deadline; }
  virtual void setDeadline (::javax::realtime::RelativeTime *);
  virtual ::javax::realtime::AsyncEventHandler *getCostOverrunHandler () { return overrunHandler; }
  virtual void setCostOverrunHandler (::javax::realtime::AsyncEventHandler *);
  virtual ::javax::realtime::AsyncEventHandler *getDeadlineMissHandler () { return missHandler; }
  virtual void setDeadlineMissHandler (::javax::realtime::AsyncEventHandler *);
  virtual jboolean setIfFeasible (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *);
public:  // actually protected
  ::javax::realtime::RelativeTime * __attribute__((aligned(__alignof__( ::java::lang::Object )))) cost;
  ::javax::realtime::RelativeTime *deadline;
  ::javax::realtime::AsyncEventHandler *overrunHandler;
  ::javax::realtime::AsyncEventHandler *missHandler;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_ReleaseParameters__ */
