// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_Scheduler__
#define __javax_realtime_Scheduler__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class RealtimeThread;
      class ProcessingGroupParameters;
      class MemoryParameters;
      class ReleaseParameters;
      class Schedulable;
      class Scheduler;
    }
  }
};

class ::javax::realtime::Scheduler : public ::java::lang::Object
{
public:  // actually protected
  Scheduler ();
  virtual jboolean addToFeasibility (::javax::realtime::Schedulable *) = 0;
public:
  virtual void fireSchedulable (::javax::realtime::Schedulable *) = 0;
  static ::javax::realtime::Scheduler *getDefaultScheduler ();
  virtual ::java::lang::String *getPolicyName () = 0;
  virtual jboolean isFeasible () = 0;
public:  // actually protected
  virtual jboolean removeFromFeasibility (::javax::realtime::Schedulable *) = 0;
public:
  static void setDefaultScheduler (::javax::realtime::Scheduler *);
  virtual jboolean setIfFeasible (::javax::realtime::Schedulable *, ::javax::realtime::ReleaseParameters *, ::javax::realtime::MemoryParameters *);
  virtual jboolean setIfFeasible (::javax::realtime::Schedulable *, ::javax::realtime::ReleaseParameters *, ::javax::realtime::MemoryParameters *, ::javax::realtime::ProcessingGroupParameters *);
public: // actually package-private
  virtual void notifyThreadStart (::javax::realtime::RealtimeThread *) { }
  virtual void notifyThreadCompletion (::javax::realtime::RealtimeThread *) { }
public:
  virtual jboolean validateSchedulingParameters (::javax::realtime::Schedulable *) = 0;
  virtual jint computeExecutionEligibility (::javax::realtime::Schedulable *) = 0;
public:  // actually protected
  static ::javax::realtime::Scheduler *defaultScheduler;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_Scheduler__ */
