// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_SchedulingParameters__
#define __javax_realtime_SchedulingParameters__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class SchedulingParameters;
    }
  }
};

class ::javax::realtime::SchedulingParameters : public ::java::lang::Object
{
public:
  SchedulingParameters ();

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_SchedulingParameters__ */
