// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_ScopedCycleException__
#define __javax_realtime_ScopedCycleException__

#pragma interface

#include <java/lang/RuntimeException.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class ScopedCycleException;
    }
  }
};

class ::javax::realtime::ScopedCycleException : public ::java::lang::RuntimeException
{
public:
  ScopedCycleException ();
  ScopedCycleException (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_ScopedCycleException__ */
