// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_SizeEstimator__
#define __javax_realtime_SizeEstimator__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class SizeEstimator;
    }
  }
};

class ::javax::realtime::SizeEstimator : public ::java::lang::Object
{
public:
  jlong getEstimate () { return estimate; }
  void reserve (::java::lang::Class *, jint);
  void reserve (::java::lang::Class *);
  void reserve (::javax::realtime::SizeEstimator *);
  void reserve (::javax::realtime::SizeEstimator *, jint);
  jint getAllocationNumber () { return allocationNumber; }
private:
  static jlong sizeOf (::java::lang::Class *);
public:
  SizeEstimator ();
public:  // actually protected
  jlong __attribute__((aligned(__alignof__( ::java::lang::Object ))))  estimate;
  jint allocationNumber;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_SizeEstimator__ */
