// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_SporadicParameters__
#define __javax_realtime_SporadicParameters__

#pragma interface

#include <javax/realtime/AperiodicParameters.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class SporadicParameters;
      class AsyncEventHandler;
      class RelativeTime;
    }
  }
};

class ::javax::realtime::SporadicParameters : public ::javax::realtime::AperiodicParameters
{
public:
  SporadicParameters (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::AsyncEventHandler *, ::javax::realtime::AsyncEventHandler *);
  virtual ::java::lang::String *getArrivalTimeQueueOverflowBehavior () { return queuePolicy; }
  virtual void setArrivalTimeQueueOverflowBehavior (::java::lang::String *);
  virtual jint getInitialArrivalTimeQueueLength () { return intialQueueLength; }
  virtual void getInitialArrivalTimeQueueLength (jint);
  virtual ::javax::realtime::RelativeTime *getMinimumInterarrival () { return minInterarrival; }
  virtual void setMinimumInterarrival (::javax::realtime::RelativeTime *);
  virtual ::java::lang::String *getMitViolationBehavior () { return mitPolicy; }
  virtual void setInitialArrivalTimeQueueLength (::java::lang::String *);
  virtual jboolean setIfFeasible (::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *, ::javax::realtime::RelativeTime *);
public:  // actually protected
  ::javax::realtime::RelativeTime * __attribute__((aligned(__alignof__( ::javax::realtime::AperiodicParameters )))) minInterarrival;
  ::java::lang::String *queuePolicy;
  ::java::lang::String *mitPolicy;
  jint intialQueueLength;
public:
  static ::java::lang::String *arrivalTimeQueueOverflowExcpt;
  static ::java::lang::String *arrivalTimeQueueOverflowIgnore;
  static ::java::lang::String *arrivalTimeQueueOverflowReplace;
  static ::java::lang::String *arrivalTimeQueueOverflowSave;
  static ::java::lang::String *mitViolationExcept;
  static ::java::lang::String *mitViolationIgnore;
  static ::java::lang::String *mitViolationReplace;
  static ::java::lang::String *mitViolationSave;

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_SporadicParameters__ */
