// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_ThrowBoundaryError__
#define __javax_realtime_ThrowBoundaryError__

#pragma interface

#include <java/lang/Error.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class ThrowBoundaryError;
    }
  }
};

class ::javax::realtime::ThrowBoundaryError : public ::java::lang::Error
{
public:
  ThrowBoundaryError ();
  ThrowBoundaryError (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_ThrowBoundaryError__ */
