// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_Timer__
#define __javax_realtime_Timer__

#pragma interface

#include <javax/realtime/AsyncEvent.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class Timer;
      class TimerImpl;
      class AbsoluteTime;
      class ReleaseParameters;
      class AsyncEventHandler;
      class HighResolutionTime;
      class Clock;
    }
  }
};

class ::javax::realtime::Timer : public ::javax::realtime::AsyncEvent
{
public:  // actually protected
  Timer (::javax::realtime::HighResolutionTime *, ::javax::realtime::Clock *, ::javax::realtime::AsyncEventHandler *);
public:
  virtual ::javax::realtime::ReleaseParameters *createReleaseParameters ();
  virtual void destroy ();
  virtual void disable ();
  virtual void enable ();
  virtual ::javax::realtime::Clock *getClock () { return clock; }
  virtual ::javax::realtime::AbsoluteTime *getFireTime ();
  virtual jboolean isRunning ();
  virtual void reschedule (::javax::realtime::HighResolutionTime *);
  virtual void start ();
  virtual jboolean stop ();
public:  // actually protected
  virtual ::javax::realtime::TimerImpl *getTimerImpl () = 0;
  ::javax::realtime::Clock * __attribute__((aligned(__alignof__( ::javax::realtime::AsyncEvent )))) clock;
  jboolean isEnabled;
  jboolean isRunning__;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_Timer__ */
