// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_TimerImpl__
#define __javax_realtime_TimerImpl__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class TimerImpl;
      class ReleaseParameters;
      class AbsoluteTime;
      class HighResolutionTime;
    }
  }
};

class ::javax::realtime::TimerImpl : public ::java::lang::Object
{
public:
  virtual void destroy () = 0;
  virtual void enable () = 0;
  virtual void disable () = 0;
  virtual jboolean isRunning () = 0;
  virtual void reschedule (::javax::realtime::HighResolutionTime *) = 0;
  virtual void start () = 0;
  virtual jboolean stop () = 0;
  virtual ::javax::realtime::AbsoluteTime *getFireTime () = 0;
  virtual ::javax::realtime::ReleaseParameters *createReleaseParameters () = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_realtime_TimerImpl__ */
