// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_UnimplementedFeatureError__
#define __javax_realtime_UnimplementedFeatureError__

#pragma interface

#include <java/lang/RuntimeException.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class UnimplementedFeatureError;
    }
  }
};

class ::javax::realtime::UnimplementedFeatureError : public ::java::lang::RuntimeException
{
public:
  UnimplementedFeatureError ();
  UnimplementedFeatureError (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_UnimplementedFeatureError__ */
