// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_UnknownHappeningException__
#define __javax_realtime_UnknownHappeningException__

#pragma interface

#include <java/lang/RuntimeException.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class UnknownHappeningException;
    }
  }
};

class ::javax::realtime::UnknownHappeningException : public ::java::lang::RuntimeException
{
public:
  UnknownHappeningException ();
  UnknownHappeningException (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_UnknownHappeningException__ */
