// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_VTMemory__
#define __javax_realtime_VTMemory__

#pragma interface

#include <javax/realtime/ScopedMemory.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class VTMemory;
    }
  }
};

class ::javax::realtime::VTMemory : public ::javax::realtime::ScopedMemory
{
public:
  VTMemory (jlong, jlong);
  virtual jlong memoryConsumed ();
  virtual jlong memoryRemaining ();
public:  // actually protected
  virtual void init ();
  virtual void fini ();
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_VTMemory__ */
