// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_util_regex_Matcher__
#define __java_util_regex_Matcher__

#pragma interface

#include <java/lang/Object.h>

class ::java::util::regex::Matcher : public ::java::lang::Object
{
public:
  virtual ::java::lang::String *replaceFirst (::java::lang::String *);
  virtual ::java::lang::String *replaceAll (::java::lang::String *);
  Matcher ();

  static ::java::lang::Class class$;
};

#endif /* __java_util_regex_Matcher__ */
