// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_util_regex_Pattern__
#define __java_util_regex_Pattern__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

class ::java::util::regex::Pattern : public ::java::lang::Object
{
public:
  static ::java::util::regex::Pattern *compile (::java::lang::String *);
  static jboolean matches (::java::lang::String *, ::java::lang::CharSequence *);
  virtual ::java::util::regex::Matcher *matcher (::java::lang::CharSequence *);
  virtual JArray< ::java::lang::String *> *split (::java::lang::CharSequence *, jint);
  Pattern ();

  static ::java::lang::Class class$;
};

#endif /* __java_util_regex_Pattern__ */
