// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_gcj_protocol_file_Connection__
#define __gnu_gcj_protocol_file_Connection__

#pragma interface

#include <java/net/URLConnection.h>

extern "Java"
{
  namespace gnu
  {
    namespace gcj
    {
      namespace protocol
      {
        namespace file
        {
          class Connection;
        }
      }
    }
  }
  namespace java
  {
    namespace net
    {
      class URL;
    }
  }
};

class ::gnu::gcj::protocol::file::Connection : public ::java::net::URLConnection
{
public:
  Connection (::java::net::URL *);
  virtual void connect ();
  virtual ::java::io::InputStream *getInputStream ();
  virtual ::java::io::OutputStream *getOutputStream ();
  virtual ::java::lang::String *getHeaderField (::java::lang::String *);
  virtual ::java::util::Map *getHeaderFields ();
  virtual ::java::lang::String *getHeaderField (jint);
  virtual ::java::lang::String *getHeaderFieldKey (jint);
private:
  ::java::lang::String *getKey (::java::lang::String *);
  ::java::lang::String *getField (::java::lang::String *);
  void getHeaders ();
  ::java::util::Hashtable * __attribute__((aligned(__alignof__( ::java::net::URLConnection )))) hdrHash;
  ::java::util::Vector *hdrVec;
  jboolean gotHeaders;
  ::java::io::File *fileIn;
  ::java::io::InputStream *inputStream;
  ::java::io::OutputStream *outputStream;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_gcj_protocol_file_Connection__ */
