# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = /home/yanxin/git/jrate/gcc/libstdc++-v3/po
top_srcdir = /home/yanxin/git/jrate/gcc/libstdc++-v3
VPATH = /home/yanxin/git/jrate/gcc/libstdc++-v3/po
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/libstdc++
pkglibdir = $(libdir)/libstdc++
pkgincludedir = $(includedir)/libstdc++

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /bin/sh /home/yanxin/git/jrate/gcc/install-sh -c
INSTALL_PROGRAM = /bin/sh /home/yanxin/git/jrate/gcc/install-sh -c  $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = /bin/sh /home/yanxin/git/jrate/gcc/install-sh -c -m 644
INSTALL_SCRIPT = /bin/sh /home/yanxin/git/jrate/gcc/install-sh -c
transform = s,^,jRate-,; 

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
AR = ar
AS = as
ATOMICITY_INC_SRCDIR = config/cpu/i486
AWK = mawk
BASIC_FILE_CC = config/io/basic_file_stdio.cc
BASIC_FILE_H = config/io/basic_file_stdio.h
CC = /home/yanxin/git/jrate/gcc-build/gcc/xgcc -B/home/yanxin/git/jrate/gcc-build/gcc/ -B/usr/local/i686-pc-linux-gnu/bin/ -B/usr/local/i686-pc-linux-gnu/lib/ -isystem /usr/local/i686-pc-linux-gnu/include
CCODECVT_C = config/io/c_io_libio_codecvt.c
CCODECVT_CC = config/locale/generic/codecvt_members.cc
CCODECVT_H = config/locale/generic/codecvt_specializations.h
CCOLLATE_CC = config/locale/generic/collate_members.cc
CCTYPE_CC = config/locale/generic/ctype_members.cc
CLOCALE_CC = config/locale/generic/c_locale.cc
CLOCALE_H = config/locale/generic/c_locale.h
CLOCALE_INTERNAL_H = config/locale/generic/c++locale_internal.h
CMESSAGES_CC = config/locale/generic/messages_members.cc
CMESSAGES_H = config/locale/generic/messages_members.h
CMONEY_CC = config/locale/generic/monetary_members.cc
CNUMERIC_CC = config/locale/generic/numeric_members.cc
CPP = /home/yanxin/git/jrate/gcc-build/gcc/xgcc -B/home/yanxin/git/jrate/gcc-build/gcc/ -B/usr/local/i686-pc-linux-gnu/bin/ -B/usr/local/i686-pc-linux-gnu/lib/ -isystem /usr/local/i686-pc-linux-gnu/include -E
CSTDIO_H = config/io/c_io_stdio.h
CTIME_CC = config/locale/generic/time_members.cc
CTIME_H = config/locale/generic/time_members.h
CXX = @CXX@
CXXCPP = /home/yanxin/git/jrate/gcc-build/gcc/xgcc -shared-libgcc -B/home/yanxin/git/jrate/gcc-build/gcc/ -nostdinc++  -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src/.libs -B/usr/local/i686-pc-linux-gnu/bin/ -B/usr/local/i686-pc-linux-gnu/lib/ -isystem /usr/local/i686-pc-linux-gnu/include -E
C_INCLUDE_DIR = ${glibcpp_srcdir}/include/c_std
DEBUG_FLAGS = 
DLLTOOL = @DLLTOOL@
EXEEXT = 
EXTRA_CXX_FLAGS = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLIBCPP_INCLUDES = -I/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/include/i686-pc-linux-gnu -I/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/include
GLIBCPP_IS_CROSS_COMPILING = false
LIBIO_INCLUDES = 
LIBMATHOBJS = 
LIBMATH_INCLUDES = -I$(top_srcdir)/libmath
LIBSUPCXX_INCLUDES = -I$(top_srcdir)/libsupc++
LIBSUPCXX_PICFLAGS = -prefer-pic
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUNWIND_FLAG = 
LN_S = ln -s
MAINT = #
MAKEINFO = /home/yanxin/git/jrate/gcc/missing makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
OPTIMIZE_CXXFLAGS = 
OPT_LDFLAGS = -Wl,-O1 
OS_INC_SRCDIR = config/os/gnu-linux
RANLIB = ranlib
SECTION_FLAGS = -ffunction-sections -fdata-sections
SECTION_LDFLAGS = 
STRIP = strip
SYMVER_MAP = config/linker-map.gnu
TOPLEVEL_INCLUDES = 
USE_NLS = no
VERSION = 3.3.3
WARN_FLAGS = -Wall -Wno-format -W -Wwrite-strings
WERROR = 
baseline_file = @baseline_file@
check_msgfmt = 
enable_shared = yes
enable_static = yes
glibcpp_CXX = /home/yanxin/git/jrate/gcc-build/gcc/xgcc -shared-libgcc -B/home/yanxin/git/jrate/gcc-build/gcc/ -nostdinc++  -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src -L/home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/src/.libs -B/usr/local/i686-pc-linux-gnu/bin/ -B/usr/local/i686-pc-linux-gnu/lib/ -isystem /usr/local/i686-pc-linux-gnu/include
glibcpp_MOFILES = 
glibcpp_POFILES = 
glibcpp_basedir = /home/yanxin/git/jrate/gcc/libstdc++-v3/.././libstdc++-v3
glibcpp_builddir = /home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3
glibcpp_localedir = /home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/po/share/locale
glibcpp_prefixdir = /usr/local
glibcpp_srcdir = /home/yanxin/git/jrate/gcc/libstdc++-v3
glibcpp_thread_h = gthr-posix.h
glibcpp_toolexecdir = $(libdir)/gcc-lib/$(target_alias)
glibcpp_toolexeclibdir = $(libdir)/.
gxx_include_dir = $(prefix)/include/c++/3.3.3
ifGNUmake = 
libio_la = 
libtool_VERSION = 5:5:0
toplevel_srcdir = ${top_srcdir}/..

PACKAGE = libstdc++

# Location of installation directories.
mkinstalldirs = $(SHELL) $(toplevel_srcdir)/mkinstalldirs
locale_installdir = $(DESTDIR)$(datadir)/locale
locale_builddir = /home/yanxin/git/jrate/gcc-build/i686-pc-linux-gnu/libstdc++-v3/po/share/locale

# Tell automake that foo.po makes foo.mo
SUFFIXES = .po .mo

LOCALE_IN = 
LOCALE_OUT = 

MSGFMT = msgfmt

# Necessary files.
DISTFILES = \
	Makefile.am Makefile.in string_literals.cc POTFILES.in $(PACKAGE).pot \
	$(LOCALE_IN) 


# Specify what gets cleaned up on a 'make clean'
CLEANFILES = $(LOCALE_OUT) 
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
CFLAGS = -O2 -g -O2
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
.SUFFIXES: .mo .po
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --cygnus po/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = po

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am:
check: check-am
installcheck-am:
installcheck: installcheck-am
install-info-am: 
install-info: install-info-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-data-local
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile all-local
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-info-am install-info \
install-exec-am install-exec install-data-local install-data-am \
install-data install-am install uninstall-am uninstall all-local \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


.po.mo:
	$(MSGFMT) -o $@ $<

all-local: all-local-no
all-local-no: 
all-local-yes: $(LOCALE_OUT) 

# 'make check' needs the catalogs constructed in build directory.
check: check-no
check-no:
check-yes:
	$(mkinstalldirs) $(locale_builddir) 
	@catalogs='$(LOCALE_OUT)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  lang=`echo $$cat | sed 's/\.mo$$//'`; \
	  install_dir=$(locale_builddir)/$$lang/LC_MESSAGES; \
	  $(mkinstalldirs) $$install_dir; \
	  $(INSTALL_DATA) $$cat $$install_dir/$(PACKAGE).mo; \
	done 

# Install rules here. 
# Wish install could just `cp -R ./share $(locale_installdir)` ...
install-data-local: install-data-local-no
install-data-local-no:
install-data-local-yes: all-local-yes
	$(mkinstalldirs) $(locale_installdir) 
	@catalogs='$(LOCALE_OUT)'; \
	for cat in $$catalogs; do \
	  cat=`basename $$cat`; \
	  lang=`echo $$cat | sed 's/\.mo$$//'`; \
	  install_dir=$(locale_installdir)/$$lang/LC_MESSAGES; \
	  $(mkinstalldirs) $$install_dir; \
	  $(INSTALL_DATA) $$cat $$install_dir/$(PACKAGE).mo; \
	done

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
