// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_nio_CharBufferImpl__
#define __gnu_java_nio_CharBufferImpl__

#pragma interface

#include <java/nio/CharBuffer.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace nio
    {
      class ByteOrder;
      class CharBuffer;
      class ByteBuffer;
    }
  }
  namespace gnu
  {
    namespace java
    {
      namespace nio
      {
        class CharBufferImpl;
      }
    }
  }
};

class ::gnu::java::nio::CharBufferImpl : public ::java::nio::CharBuffer
{
public:
  CharBufferImpl (jint, jint, jint);
  CharBufferImpl (jcharArray, jint, jint);
  CharBufferImpl (::gnu::java::nio::CharBufferImpl *);
private:
  static jcharArray nio_cast (jbyteArray);
public: // actually package-private
  CharBufferImpl (jbyteArray);
private:
  static jbyte nio_get_Byte (::gnu::java::nio::CharBufferImpl *, jint, jint);
  static void nio_put_Byte (::gnu::java::nio::CharBufferImpl *, jint, jint, jbyte);
public:
  ::java::nio::ByteBuffer *asByteBuffer ();
  jboolean isReadOnly () { return readOnly; }
  ::java::nio::CharBuffer *slice ();
  ::java::nio::CharBuffer *duplicate ();
  ::java::nio::CharBuffer *asReadOnlyBuffer ();
  ::java::nio::CharBuffer *compact () { return reinterpret_cast< ::java::nio::CharBuffer *> (this); }
  jboolean isDirect ();
  ::java::lang::CharSequence *subSequence (jint, jint);
  jchar get ();
  ::java::nio::CharBuffer *put (jchar);
  jchar get (jint);
  ::java::nio::CharBuffer *put (jint, jchar);
  ::java::nio::ByteOrder *order ();
private:
  jboolean __attribute__((aligned(__alignof__( ::java::nio::CharBuffer ))))  readOnly;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_nio_CharBufferImpl__ */
