// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_nio_IntBufferImpl__
#define __gnu_java_nio_IntBufferImpl__

#pragma interface

#include <java/nio/IntBuffer.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace nio
    {
      class ByteOrder;
      class IntBuffer;
      class ByteBuffer;
    }
  }
  namespace gnu
  {
    namespace java
    {
      namespace nio
      {
        class IntBufferImpl;
      }
    }
  }
};

class ::gnu::java::nio::IntBufferImpl : public ::java::nio::IntBuffer
{
public:
  IntBufferImpl (jint, jint, jint);
  IntBufferImpl (jintArray, jint, jint);
  IntBufferImpl (::gnu::java::nio::IntBufferImpl *);
private:
  static jintArray nio_cast (jbyteArray);
public: // actually package-private
  IntBufferImpl (jbyteArray);
private:
  static jbyte nio_get_Byte (::gnu::java::nio::IntBufferImpl *, jint, jint);
  static void nio_put_Byte (::gnu::java::nio::IntBufferImpl *, jint, jint, jbyte);
public:
  ::java::nio::ByteBuffer *asByteBuffer ();
  jboolean isReadOnly () { return readOnly; }
  ::java::nio::IntBuffer *slice ();
  ::java::nio::IntBuffer *duplicate ();
  ::java::nio::IntBuffer *asReadOnlyBuffer ();
  ::java::nio::IntBuffer *compact () { return reinterpret_cast< ::java::nio::IntBuffer *> (this); }
  jboolean isDirect ();
  jint get ();
  ::java::nio::IntBuffer *put (jint);
  jint get (jint);
  ::java::nio::IntBuffer *put (jint, jint);
  ::java::nio::ByteOrder *order ();
private:
  jboolean __attribute__((aligned(__alignof__( ::java::nio::IntBuffer ))))  readOnly;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_nio_IntBufferImpl__ */
