// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_nio_LongBufferImpl__
#define __gnu_java_nio_LongBufferImpl__

#pragma interface

#include <java/nio/LongBuffer.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace nio
    {
      class ByteOrder;
      class LongBuffer;
      class ByteBuffer;
    }
  }
  namespace gnu
  {
    namespace java
    {
      namespace nio
      {
        class LongBufferImpl;
      }
    }
  }
};

class ::gnu::java::nio::LongBufferImpl : public ::java::nio::LongBuffer
{
public:
  LongBufferImpl (jint, jint, jint);
  LongBufferImpl (jlongArray, jint, jint);
  LongBufferImpl (::gnu::java::nio::LongBufferImpl *);
private:
  static jlongArray nio_cast (jbyteArray);
public: // actually package-private
  LongBufferImpl (jbyteArray);
private:
  static jbyte nio_get_Byte (::gnu::java::nio::LongBufferImpl *, jint, jint);
  static void nio_put_Byte (::gnu::java::nio::LongBufferImpl *, jint, jint, jbyte);
public:
  ::java::nio::ByteBuffer *asByteBuffer ();
  jboolean isReadOnly () { return readOnly; }
  ::java::nio::LongBuffer *slice ();
  ::java::nio::LongBuffer *duplicate ();
  ::java::nio::LongBuffer *asReadOnlyBuffer ();
  ::java::nio::LongBuffer *compact () { return reinterpret_cast< ::java::nio::LongBuffer *> (this); }
  jboolean isDirect ();
  jlong get ();
  ::java::nio::LongBuffer *put (jlong);
  jlong get (jint);
  ::java::nio::LongBuffer *put (jint, jlong);
  ::java::nio::ByteOrder *order ();
private:
  jboolean __attribute__((aligned(__alignof__( ::java::nio::LongBuffer ))))  readOnly;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_nio_LongBufferImpl__ */
