// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_nio_ShortBufferImpl__
#define __gnu_java_nio_ShortBufferImpl__

#pragma interface

#include <java/nio/ShortBuffer.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace nio
    {
      class ByteOrder;
      class ShortBuffer;
      class ByteBuffer;
    }
  }
  namespace gnu
  {
    namespace java
    {
      namespace nio
      {
        class ShortBufferImpl;
      }
    }
  }
};

class ::gnu::java::nio::ShortBufferImpl : public ::java::nio::ShortBuffer
{
public:
  ShortBufferImpl (jint, jint, jint);
  ShortBufferImpl (jshortArray, jint, jint);
  ShortBufferImpl (::gnu::java::nio::ShortBufferImpl *);
private:
  static jshortArray nio_cast (jbyteArray);
public: // actually package-private
  ShortBufferImpl (jbyteArray);
private:
  static jbyte nio_get_Byte (::gnu::java::nio::ShortBufferImpl *, jint, jint);
  static void nio_put_Byte (::gnu::java::nio::ShortBufferImpl *, jint, jint, jbyte);
public:
  ::java::nio::ByteBuffer *asByteBuffer ();
  jboolean isReadOnly () { return readOnly; }
  ::java::nio::ShortBuffer *slice ();
  ::java::nio::ShortBuffer *duplicate ();
  ::java::nio::ShortBuffer *asReadOnlyBuffer ();
  ::java::nio::ShortBuffer *compact () { return reinterpret_cast< ::java::nio::ShortBuffer *> (this); }
  jboolean isDirect ();
  jshort get ();
  ::java::nio::ShortBuffer *put (jshort);
  jshort get (jint);
  ::java::nio::ShortBuffer *put (jint, jshort);
  ::java::nio::ByteOrder *order ();
private:
  jboolean __attribute__((aligned(__alignof__( ::java::nio::ShortBuffer ))))  readOnly;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_nio_ShortBufferImpl__ */
