// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_util_CountableEventVariable__
#define __javax_realtime_util_CountableEventVariable__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      namespace util
      {
        class CountableEventVariable;
      }
    }
  }
};

class ::javax::realtime::util::CountableEventVariable : public ::java::lang::Object
{
public:
  CountableEventVariable ();
  CountableEventVariable (jint);
  virtual void await ();
  virtual void await (jlong);
  virtual void await (jlong, jint);
  virtual void signal ();
  virtual void broadCastSignal ();
  virtual jint getCount ();
private:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  eventCount;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_util_CountableEventVariable__ */
