// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_util_EventVariable__
#define __javax_realtime_util_EventVariable__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      namespace util
      {
        class EventVariable;
      }
    }
  }
};

class ::javax::realtime::util::EventVariable : public ::java::lang::Object
{
public:
  EventVariable ();
  EventVariable (jboolean);
  virtual void await ();
  virtual void await (jlong);
  virtual void await (jlong, jint);
  virtual void signal ();
  virtual void broadCastSignal ();
private:
  jboolean __attribute__((aligned(__alignof__( ::java::lang::Object ))))  signaled;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_util_EventVariable__ */
