// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_util_Executor__
#define __javax_realtime_util_Executor__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      namespace util
      {
        class Executor;
      }
    }
  }
};

class ::javax::realtime::util::Executor : public ::java::lang::Object
{
public:
  virtual void execute (::java::lang::Runnable *) = 0;
  virtual void shutdown () = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_realtime_util_Executor__ */
