// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_util_ShutdownExecutorException__
#define __javax_realtime_util_ShutdownExecutorException__

#pragma interface

#include <java/lang/Exception.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      namespace util
      {
        class ShutdownExecutorException;
      }
    }
  }
};

class ::javax::realtime::util::ShutdownExecutorException : public ::java::lang::Exception
{
public:
  ShutdownExecutorException ();
  ShutdownExecutorException (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_util_ShutdownExecutorException__ */
