// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_util_ThreadedExecutor__
#define __javax_realtime_util_ThreadedExecutor__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      namespace util
      {
        class ThreadedExecutor;
      }
      class Scheduler;
      class ProcessingGroupParameters;
      class MemoryArea;
      class SchedulingParameters;
      class ReleaseParameters;
      class MemoryParameters;
    }
  }
};

class ::javax::realtime::util::ThreadedExecutor : public ::java::lang::Object
{
public:
  ThreadedExecutor ();
  ThreadedExecutor (::javax::realtime::SchedulingParameters *, ::javax::realtime::ReleaseParameters *, ::javax::realtime::MemoryParameters *, ::javax::realtime::MemoryArea *, ::javax::realtime::ProcessingGroupParameters *, jboolean);
  virtual void execute (::java::lang::Runnable *);
  virtual jboolean addIfFeasible ();
  virtual jboolean addToFeasibility ();
  virtual ::javax::realtime::MemoryParameters *getMemoryParameters () { return memoryParam; }
  virtual void setMemoryParameters (::javax::realtime::MemoryParameters *);
  virtual jboolean setMemoryParametersIfFeasible (::javax::realtime::MemoryParameters *);
  virtual ::javax::realtime::ProcessingGroupParameters *getProcessingGroupParameters () { return groupParam; }
  virtual void setProcessingGroupParameters (::javax::realtime::ProcessingGroupParameters *);
  virtual jboolean setProcessingGroupParametersIfFeasible (::javax::realtime::ProcessingGroupParameters *);
  virtual ::javax::realtime::ReleaseParameters *getReleaseParameters () { return releaseParam; }
  virtual void setReleaseParameters (::javax::realtime::ReleaseParameters *);
  virtual jboolean setReleaseParametersIfFeasible (::javax::realtime::ReleaseParameters *);
  virtual ::javax::realtime::Scheduler *getScheduler () { return scheduler; }
  virtual void setScheduler (::javax::realtime::Scheduler *);
  virtual void setScheduler (::javax::realtime::Scheduler *, ::javax::realtime::SchedulingParameters *, ::javax::realtime::ReleaseParameters *, ::javax::realtime::MemoryParameters *, ::javax::realtime::ProcessingGroupParameters *);
  virtual ::javax::realtime::SchedulingParameters *getSchedulingParameters () { return schedulingParam; }
  virtual void setSchedulingParameters (::javax::realtime::SchedulingParameters *);
  virtual jboolean setSchedulingParametersIfFeasible (::javax::realtime::SchedulingParameters *);
  virtual jboolean removeFromFeasibility ();
public:  // actually protected
  ::javax::realtime::MemoryParameters * __attribute__((aligned(__alignof__( ::java::lang::Object )))) memoryParam;
  ::javax::realtime::ReleaseParameters *releaseParam;
  ::javax::realtime::SchedulingParameters *schedulingParam;
  ::javax::realtime::MemoryArea *memoryArea;
  ::javax::realtime::ProcessingGroupParameters *groupParam;
  ::javax::realtime::Scheduler *scheduler;
  jboolean noHeap;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_util_ThreadedExecutor__ */
