// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_realtime_util_ThreadBoundExecutor__
#define __javax_realtime_util_ThreadBoundExecutor__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace realtime
    {
      class Scheduler;
      class ProcessingGroupParameters;
      class MemoryArea;
      class MemoryParameters;
      class ReleaseParameters;
      class SchedulingParameters;
      namespace util
      {
        class ThreadBoundExecutor;
        class ThreadBoundExecutor$ExecutorLogic;
      }
      class RealtimeThread;
    }
  }
};

class ::javax::realtime::util::ThreadBoundExecutor : public ::java::lang::Object
{
public:
  ThreadBoundExecutor (::javax::realtime::SchedulingParameters *, ::javax::realtime::ReleaseParameters *, ::javax::realtime::MemoryParameters *, ::javax::realtime::MemoryArea *, ::javax::realtime::ProcessingGroupParameters *, jboolean);
  ThreadBoundExecutor (::javax::realtime::SchedulingParameters *);
  virtual void execute (::java::lang::Runnable *);
  virtual void shutdown ();
  virtual void run () { }
  virtual jboolean addIfFeasible ();
  virtual jboolean addToFeasibility ();
  virtual ::javax::realtime::MemoryParameters *getMemoryParameters ();
  virtual void setMemoryParameters (::javax::realtime::MemoryParameters *);
  virtual jboolean setMemoryParametersIfFeasible (::javax::realtime::MemoryParameters *);
  virtual ::javax::realtime::ProcessingGroupParameters *getProcessingGroupParameters ();
  virtual void setProcessingGroupParameters (::javax::realtime::ProcessingGroupParameters *);
  virtual jboolean setProcessingGroupParametersIfFeasible (::javax::realtime::ProcessingGroupParameters *);
  virtual ::javax::realtime::ReleaseParameters *getReleaseParameters ();
  virtual void setReleaseParameters (::javax::realtime::ReleaseParameters *);
  virtual jboolean setReleaseParametersIfFeasible (::javax::realtime::ReleaseParameters *);
  virtual ::javax::realtime::Scheduler *getScheduler ();
  virtual void setScheduler (::javax::realtime::Scheduler *);
  virtual void setScheduler (::javax::realtime::Scheduler *, ::javax::realtime::SchedulingParameters *, ::javax::realtime::ReleaseParameters *, ::javax::realtime::MemoryParameters *, ::javax::realtime::ProcessingGroupParameters *);
  virtual ::javax::realtime::SchedulingParameters *getSchedulingParameters ();
  virtual void setSchedulingParameters (::javax::realtime::SchedulingParameters *);
  virtual jboolean setSchedulingParametersIfFeasible (::javax::realtime::SchedulingParameters *);
  virtual jboolean removeFromFeasibility ();
  virtual jint executionEligibility ();
public:  // actually protected
  ::javax::realtime::RealtimeThread * __attribute__((aligned(__alignof__( ::java::lang::Object )))) thread;
  jboolean active;
  ::javax::realtime::util::ThreadBoundExecutor$ExecutorLogic *executorLogic;
  jint executionEligibility__;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_realtime_util_ThreadBoundExecutor__ */
