// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_security_Policy__
#define __java_security_Policy__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace java
  {
    namespace security
    {
      class PermissionCollection;
      class CodeSource;
      class Policy;
    }
  }
};

class ::java::security::Policy : public ::java::lang::Object
{
public:
  Policy ();
  static ::java::security::Policy *getPolicy ();
  static void setPolicy (::java::security::Policy *);
  virtual ::java::security::PermissionCollection *getPermissions (::java::security::CodeSource *) = 0;
  virtual void refresh () = 0;
private:
  static ::java::security::Policy *currentPolicy;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_security_Policy__ */
