// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_StringBuffer__
#define __java_lang_StringBuffer__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

class ::java::lang::StringBuffer : public ::java::lang::Object
{
public:
  ::java::lang::StringBuffer *append (jboolean);
  ::java::lang::StringBuffer *append (jchar);
  ::java::lang::StringBuffer *append (jint);
  ::java::lang::StringBuffer *append (jlong);
  ::java::lang::StringBuffer *append (jfloat);
  ::java::lang::StringBuffer *append (jdouble);
  ::java::lang::StringBuffer *append (::java::lang::Object *);
  ::java::lang::StringBuffer *append (::java::lang::String *);
  ::java::lang::StringBuffer *append (::java::lang::StringBuffer *);
  ::java::lang::StringBuffer *append (jcharArray);
  ::java::lang::StringBuffer *append (jcharArray, jint, jint);
  jint capacity ();
  jchar charAt (jint);
  ::java::lang::StringBuffer *delete$ (jint, jint);
  ::java::lang::StringBuffer *deleteCharAt (jint);
  void ensureCapacity (jint);
private:
  void ensureCapacity_unsynchronized (jint);
public:
  void getChars (jint, jint, jcharArray, jint);
  ::java::lang::StringBuffer *insert (jint, jboolean);
  ::java::lang::StringBuffer *insert (jint, jchar);
  ::java::lang::StringBuffer *insert (jint, jint);
  ::java::lang::StringBuffer *insert (jint, jlong);
  ::java::lang::StringBuffer *insert (jint, jfloat);
  ::java::lang::StringBuffer *insert (jint, jdouble);
  ::java::lang::StringBuffer *insert (jint, ::java::lang::Object *);
  ::java::lang::StringBuffer *insert (jint, ::java::lang::String *);
  ::java::lang::StringBuffer *insert (jint, jcharArray);
  ::java::lang::StringBuffer *insert (jint, jcharArray, jint, jint);
  jint length () { return count; }
  ::java::lang::StringBuffer *replace (jint, jint, ::java::lang::String *);
  ::java::lang::StringBuffer *reverse ();
  void setCharAt (jint, jchar);
  void setLength (jint);
  StringBuffer ();
  StringBuffer (jint);
  StringBuffer (::java::lang::String *);
  ::java::lang::String *substring (jint);
  ::java::lang::String *substring (jint, jint);
  ::java::lang::CharSequence *subSequence (jint, jint);
  ::java::lang::String *toString ();
public: // actually package-private
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  count;
  jcharArray value;
  jboolean shared;
  static const jlong serialVersionUID = 3388685877147921107LL;
private:
  static const jint DEFAULT_CAPACITY = 16L;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_lang_StringBuffer__ */
